.github/workflows/ci.yml
src/lib.rs
src/main.rs

I think we should deny warnings and documentation in CI. In general, I think these are good defaults, and it is more convenient for development to do that in CI, rather than adding `#[deny(...)]` to the crates. What do you think?

Deny `warnings` and `missing-docs` in CI

---

bin/inx-chronicle/src/main.rs
src/runtime/actor/error.rs
src/runtime/actor/report.rs
src/runtime/error.rs
src/runtime/scope.rs

Adds the actor type to the error enum so that no weird downcasting is needed in supervisor error handling.

Add type to `ActorError`

---

bin/inx-chronicle/src/main.rs

Add a panic hook to print panics in a way that doesn't disrupt our logging.
```
[2022-04-22T11:53:37Z DEBUG inx_chronicle::api] inx_chronicle::api::ApiWorker shutting down (376e36fd-68b7-460f-8a1d-239832f157f4)
thread '[2022-04-22T11:53:37Z DEBUG chronicle::runtime::actor] inx_chronicle::broker::Broker exited event loop (adc3cac4-845b-4000-8cae-cd6b52eb8795)
tokio-runtime-worker[2022-04-22T11:53:37Z DEBUG h2::codec::framed_write] send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
[2022-04-22T11:53:38Z DEBUG chronicle::runtime::actor] inx_chronicle::broker::Broker shutting down (adc3cac4-845b-4000-8cae-cd6b52eb8795)
[2022-04-22T11:53:38Z DEBUG chronicle::runtime::scope] Joining scope adc3cac4
[2022-04-22T11:53:38Z DEBUG h2::proto::connection] Connection::poll; …
```

Add panic hook

---

bin/inx-chronicle/src/inx/listener.rs
bin/inx-chronicle/src/inx/worker.rs
bin/inx-chronicle/src/main.rs
src/runtime/actor/addr.rs
src/runtime/actor/context.rs
src/runtime/actor/error.rs
src/runtime/actor/event.rs
src/runtime/actor/mod.rs
src/runtime/actor/report.rs
src/runtime/actor/util.rs
src/runtime/config.rs
src/runtime/error.rs
src/runtime/registry.rs
src/runtime/scope.rs

This solves two problems:
1. The registry is now scoped along with the actors, so hierarchical design can be maintained.
2. Spawning actors now automatically adds the address to the registry (unless specified otherwise) so the `SpawnActor` event does not need to do anything special.

Add Address Registry to the runtime

---

bin/inx-chronicle/src/api/mod.rs
bin/inx-chronicle/src/launcher.rs
bin/inx-chronicle/src/metrics.rs
bin/inx-chronicle/src/stardust_inx/config.rs
bin/inx-chronicle/src/stardust_inx/mod.rs
bin/inx-chronicle/src/stardust_inx/syncer.rs
src/runtime/actor/addr.rs
src/runtime/actor/context.rs
src/runtime/registry.rs
src/runtime/scope.rs

Previously, an aborted actor would try to exit via the shutdown handle, but this would not abort if the actor is waiting in `init`. This change avoid using the shutdown handle until the actor has completed `init`, thus the abort handle is used instead during that time.

feat(runtime)!: make actors abortable from init

---

Cargo.toml
README.md
bin/inx-chronicle/config.template.toml
bin/inx-chronicle/src/api/config.rs
bin/inx-chronicle/src/cli.rs
bin/inx-chronicle/src/config.rs
bin/inx-chronicle/src/launcher.rs
bin/inx-chronicle/src/metrics.rs
bin/inx-chronicle/src/stardust_inx/config.rs

The override order is as follows (from lowest to highest priority):
- `config.toml` file
- `.env` file
- CLI parameter
NOTE: the features (api/inx/metrics) have to be compiled into the binary. For features that aren't there the flags will just be ignored.
Closes #387.

feat(config): set `api`, `inx`, `metrics` features dynamically

---

.cargo/config.toml
.github/workflows/_build.yml
.github/workflows/_check.yml
.github/workflows/canary.yml
.github/workflows/ci.yml
Cargo.toml
bin/inx-chronicle/src/api/extractors.rs
bin/inx-chronicle/src/api/responses.rs
bin/inx-chronicle/src/api/routes.rs
bin/inx-chronicle/src/api/stardust/history/routes.rs
bin/inx-chronicle/src/api/stardust/mod.rs
bin/inx-chronicle/src/launcher.rs
src/db/collections/block.rs
src/db/collections/ledger_update.rs
src/db/mod.rs
src/types/mod.rs

fix(ci): improve feature handling and CI

---

bin/inx-chronicle/src/api/stardust/core/responses.rs
bin/inx-chronicle/src/api/stardust/core/routes.rs
bin/inx-chronicle/src/api/stardust/explorer/responses.rs
bin/inx-chronicle/src/api/stardust/explorer/routes.rs
docs/api-explorer.yml

fix(api): move `children` endpoint to Explorer API

---

src/bin/inx-chronicle/api/stardust/core/routes.rs

fix(api): remove `u32` from `transaction-included-block` endpoint

---

.cargo/config.toml
.github/workflows/canary.yml
.github/workflows/ci.yml

fix(ci): install protoc in `udeps` workflow

---

Cargo.toml
src/bin/inx-chronicle/api/routes.rs
src/bin/inx-chronicle/api/stardust/analytics/routes.rs
src/bin/inx-chronicle/api/stardust/core/routes.rs
src/bin/inx-chronicle/api/stardust/explorer/routes.rs
src/bin/inx-chronicle/api/stardust/indexer/routes.rs
src/bin/inx-chronicle/launcher.rs
src/bin/inx-chronicle/stardust_inx/chunks.rs
src/bin/inx-chronicle/stardust_inx/mod.rs
src/db/collections/block.rs
src/db/collections/ledger_update.rs
src/db/collections/milestone.rs
src/db/collections/mod.rs
src/db/collections/outputs/indexer/mod.rs
src/db/collections/outputs/mod.rs
src/db/collections/protocol_update.rs
src/db/collections/treasury.rs
src/db/mongodb.rs
tests/blocks.rs
tests/milestones.rs
tests/outputs.rs

This PR creates individual types for each DB collection. In order to make it as clean as possible, I created a new API trait `MongoDbCollection` to enable calling genericised functions and convert the underlying collection types.
These collections have a small quirk: Some of their methods need to access more than one collection. For this reason, some of them hold multiple mongodb `Collections`. There is probably a better way to do this.
Additionally, I added a thread-safe version of the chunks iterator from `itertools` which mostly works. Sometimes it causes inexplicable errors in the wrong locations, but I believe these are actually compiler bugs and not real issues. Either way, there is only one location where it was necessary to work around this: inserting treasury payloads.
I have …

feat(db): separate database collections into individual types

---

src/bin/inx-chronicle/config.rs

fix(config): override mongodb `connect_url` (and not the config) when given as CLI arg

---

documentation/docusaurus.config.js

We need to use the same subpath in all versions so that the wiki can determine the existing versions

docs(wiki): change Chronicle path to be compatible with other versions

---

documentation/api/api-analytics.yml
src/bin/inx-chronicle/api/stardust/analytics/responses.rs
src/bin/inx-chronicle/api/stardust/analytics/routes.rs
src/db/collections/outputs/mod.rs
tests/claiming.rs

feat: add `claiming` endpoint to `anlytics/v2`

---

documentation/docusaurus.config.js

With wiki V3 we can get rid of this. Chronicle docs for Shimmer will be hosted under /shimmer/chronicle/...

doc(wiki): remove version info

---

src/types/mod.rs

This should fix the broken canary build again.

fix(types): conditionally import `context`

---

docker/docker-compose.yml

fix(docker): scale InfluxDB to bigger data

---

src/db/collections/analytics/mod.rs

This fn is actually not used anywhere, so we can delete it instead if you think we'll never need it. Opinions?

fix(db): total byte cost calculation

---

docker/assets/grafana/dashboards/chronicle_dashboard.json

This PR fixes the display of the `analytics_time` next to the `milestone_time`.

fix(grafana): show both `metrics` and `analytics` time

---

src/db/collections/outputs/mod.rs

This is a hotfix taken from #924. This fixes a problem with miscounted changed aliases and NFTs in our analytics.

fix(analytics)!: correctly count aliases and NFT activity

---

src/bin/inx-chronicle/stardust_inx/mod.rs

Daily active addresses were not computed because we recreated the `Vec` of analytics for each ledger update, leading to a reset of `current_date`.

fix(analytics): computation of daily active addresses

---

src/inx/raw.rs
src/types/ledger/output_metadata.rs

This is to satisfy future versions of `clippy`.

chore(clippy): fix `Display` formatting

---

src/bin/inx-chronicle/api/error.rs
src/bin/inx-chronicle/api/routes.rs

This should fix our canary CI pipeline.

fix(ci): fix `format` arguments

---

documentation/api/api-explorer.yml
src/bin/inx-chronicle/api/stardust/explorer/responses.rs
src/bin/inx-chronicle/api/stardust/explorer/routes.rs
src/db/collections/block.rs

feat(api)!: add payload type to `block_by_milestone`

---

Cargo.lock
docker/assets/grafana/dashboards/analytics_dashboard.json
src/analytics/influx.rs
src/analytics/ledger/active_addresses.rs
src/analytics/ledger/address_balance.rs
src/analytics/ledger/base_token.rs
src/analytics/ledger/ledger_outputs.rs
src/analytics/ledger/ledger_size.rs
src/analytics/ledger/mod.rs
src/analytics/ledger/output_activity.rs
src/analytics/ledger/transaction_size.rs
src/analytics/ledger/unclaimed_tokens.rs
src/analytics/ledger/unlock_conditions.rs
src/analytics/mod.rs
src/analytics/tangle/block_activity.rs
src/analytics/tangle/milestone_size.rs
src/analytics/tangle/mod.rs
src/analytics/tangle/protocol_params.rs
src/bin/inx-chronicle/cli/analytics.rs
src/bin/inx-chronicle/cli/mod.rs
src/db/collections/outputs/indexer/mod.rs
src/db/collections/outputs/mod.rs
src/db/influxdb/config.rs
src/tangle/sources/mongodb.rs

This PR adds the `fill-daily-analytics` command to the CLI and removes daily calculations from the regular workflow, including during syncing. This means the only way to gather daily analytics is by calling the CLI command.
This PR adds two additional indexes to support querying for outputs by timestamp.
There are two main issues with using per-milestone data to calculate daily analytics.
1. The date transitions are not simple. We can only know that we should calculate a date by having two milestones and comparing the dates. This creates situations where it is possible to miss analytics even when syncing. Moreover, the code to support these calculations is over-complex.
2. Filling analytics per-milestone using tasks can miss date transitions, as one task can finish on the last milestone …

fix(analytics): fill daily analytics

---

src/bin/inx-chronicle/cli/analytics.rs
src/bin/inx-chronicle/cli/api.rs
src/bin/inx-chronicle/cli/mod.rs

This PR re-merges `fill-analytics` and `fill-interval-analytics` while also allowing the `--start-date` and `--end-date` flags to determine the start and end milestones for per-milestone analytics. The rules for this are outlined in the CLI docs:
```
This commands accepts both milestone index and date ranges. The following rules apply:
- If both milestone and date are specified, the date will be used for interval analytics
while the milestone will be used for per-milestone analytics.
- If only the milestone is specified, the date will be inferred from the milestone timestamp.
- If only the date is specified, the milestone will be inferred from the available data from that date.
- If neither are specified, then the entire range of available data will be used.
```
I wish I had thought to do …

feat(cli)!: consolidate fill analytics once again

---

src/bin/inx-chronicle/main.rs
src/bin/inx-chronicle/migrations/mod.rs

fix(api): only perform write ops if a write feature is enabled

---

src/bin/inx-chronicle/main.rs

fix: forward worker errors to main exit code

---

src/bin/inx-chronicle/main.rs

I think "Shutdown successful" was confusing to people. We can circumvent this by being more accurate in logging that all our tasks have successfully resolved due to the shutdown/abort signal.

chore(logging): rephrase logs during shutdown

---

docker/docker-compose.yml

The current config as below does not work as of hornet config file not found error
`- "-c ${HORNET_CONFIG_PATH}"`
but this works well:
`- "--config=${HORNET_CONFIG_PATH}"`

Fix the hornet config specification
