iotaledger/inx-chronicle

.cargo/audit.toml
=> Ignore vulnerabilities `RUSTSEC-2020-0071`, `RUSTSEC-2020-0159`

.github/workflows/release.yml
This reverts commit 97914e0021e0757649f16d050a9445f72576481b.
=> Revert "Remove cross-plattform Docker images (#60)"

bin/inx-chronicle/src/api/mod.rs, src/lib.rs, src/runtime/actor/event.rs, src/runtime/actor/mod.rs, src/runtime/config.rs, src/runtime/registry.rs, src/runtime/shutdown.rs, src/types/stardust/message/output/alias.rs
I like keeping things as private as possible.
=> fix: `unreachable_pub` instances and add compiler warning

bin/inx-chronicle/src/collector/mod.rs, bin/inx-chronicle/src/collector/stardust_inx/mod.rs
=> fix: Make `solidifiers` immutable

bin/inx-chronicle/src/api/mod.rs, bin/inx-chronicle/src/api/stardust/analytics/mod.rs, bin/inx-chronicle/src/api/stardust/explorer/mod.rs, bin/inx-chronicle/src/api/stardust/mod.rs, bin/inx-chronicle/src/api/stardust/v2/mod.rs, bin/inx-chronicle/src/collector/mod.rs, bin/inx-chronicle/src/collector/stardust_inx/mod.rs, bin/inx-chronicle/src/main.rs, src/db/mod.rs, src/runtime/actor/mod.rs
=> chore: use `self::` everywhere

bin/inx-chronicle/src/metrics.rs
It's too much effort getting `ps` to work in the distroless container.
=> Remove process metrics

docker/Dockerfile, docker/config.hornet.json, docker/docker-compose.hornet.yml
* `docker-compose.hornet.yml` now points to `iotaledger/hornet`
* some port fixes
=> chore(docker)!: fix and document ports

bin/inx-chronicle/src/launcher.rs, bin/inx-chronicle/src/stardust_inx/error.rs, bin/inx-chronicle/src/stardust_inx/mod.rs
Adds back knocking on Hornet's door every 5s for all eternity.
=> feat(inx): retry on INX connection errors

src/runtime/scope.rs
=> fix(runtime): use `warn!` instead of `error!`

bin/inx-chronicle/src/api/error.rs, bin/inx-chronicle/src/api/stardust/history/extractors.rs, bin/inx-chronicle/src/api/stardust/history/responses.rs, bin/inx-chronicle/src/api/stardust/history/routes.rs
=> fix(api)!: TIP compliance for `history` API fields

bin/inx-chronicle/src/api/stardust/core/routes.rs, src/db/collections/milestone.rs
=> fix(api): clean up receipt route handlers and db queries

Cargo.lock, bin/inx-chronicle/src/api/stardust/core/routes.rs, bin/inx-chronicle/src/api/stardust/history/extractors.rs, bin/inx-chronicle/src/api/stardust/history/responses.rs, bin/inx-chronicle/src/api/stardust/history/routes.rs, src/db/collections/ledger_update.rs, src/db/collections/milestone.rs, src/db/collections/mod.rs, src/types/tangle/milestone_index.rs
=> feat(api): add `ledger/updates/by-milestone` endpoint

bin/inx-chronicle/src/api/stardust/history/extractors.rs
=> fix(api): add serde rename on fields

bin/inx-chronicle/src/api/error.rs, bin/inx-chronicle/src/api/stardust/history/extractors.rs, bin/inx-chronicle/src/api/stardust/history/routes.rs
=> feat(api): support sort option in queries

bin/inx-chronicle/src/api/stardust/history/routes.rs, src/db/collections/ledger_update.rs
Might fix mem issue mentioned in #370
=> fix(db): fix sorted paginated ledger update queries

bin/inx-chronicle/src/api/responses.rs, bin/inx-chronicle/src/api/stardust/analytics/responses.rs, bin/inx-chronicle/src/api/stardust/analytics/routes.rs, bin/inx-chronicle/src/api/stardust/core/responses.rs, bin/inx-chronicle/src/api/stardust/history/extractors.rs, bin/inx-chronicle/src/api/stardust/history/responses.rs, src/types/ledger/conflict_reason.rs, src/types/ledger/inclusion_state.rs, src/types/stardust/block/address/mod.rs, src/types/stardust/block/input.rs, src/types/stardust/block/output/feature.rs, src/types/stardust/block/output/mod.rs, src/types/stardust/block/output/native_token.rs, src/types/stardust/block/output/unlock_condition.rs, src/types/stardust/block/payload/milestone/mod.rs, src/types/stardust/block/payload/mod.rs, src/types/stardust/block/payload/transaction.rs, src/types/stardust/block/signature.rs, src/types/stardust/block/unlock.rs
=> chore: use serde rename_all on types

Cargo.toml, docker/.gitignore, docker/config.hornet.json, docker/docker-compose.hornet.yml, docker/docker-compose.monitoring.yml, docker/monitoring/prometheus.yml, src/runtime/actor/mod.rs, src/runtime/actor/sender.rs, src/runtime/actor/util.rs, src/runtime/scope.rs
=> feat(metrics): differentiate b/n `metrics` and `metrics-debug`

src/db/collections/ledger_update.rs, src/types/stardust/block/output/mod.rs, src/types/stardust/block/output/unlock_condition.rs
=> fix(db): add `unlock_condition` to `id_index`

bin/inx-chronicle/src/api/error.rs, bin/inx-chronicle/src/launcher.rs, bin/inx-chronicle/src/stardust_inx/error.rs, src/runtime/actor/mod.rs, src/runtime/error.rs, src/runtime/mod.rs, src/runtime/scope.rs, src/runtime/task/mod.rs
=> fix: add `ErrorLevel` trait to specify error log levels

bin/inx-chronicle/src/cli.rs, bin/inx-chronicle/src/config.rs, bin/inx-chronicle/src/launcher.rs
=> fix: properly merge `ENV` and `config.template.toml`

bin/inx-chronicle/config.template.toml, bin/inx-chronicle/src/api/routes.rs, bin/inx-chronicle/src/api/stardust/analytics/routes.rs, bin/inx-chronicle/src/api/stardust/core/routes.rs, src/db/collections/milestone.rs
=> fix(api): remove `inx` from `is_healthy` check

bin/inx-chronicle/src/api/routes.rs
Some bike-shedding, yes, but I was just in the mood :trollface:
=> refactor(api): slightly improve `is_healthy` fn

src/types/stardust/block/payload/transaction.rs
=> fix(types): inputs commitment conversion

bin/inx-chronicle/src/api/error.rs, bin/inx-chronicle/src/api/extractors.rs, bin/inx-chronicle/src/api/mod.rs, bin/inx-chronicle/src/api/stardust/history/extractors.rs, bin/inx-chronicle/src/api/stardust/indexer/extractors.rs, bin/inx-chronicle/src/api/stardust/mod.rs, src/db/collections/ledger_update.rs, src/db/collections/mod.rs, src/db/collections/outputs/indexer/alias.rs, src/db/collections/outputs/indexer/basic.rs, src/db/collections/outputs/indexer/foundry.rs, src/db/collections/outputs/indexer/nft.rs
=> fix(api): add max page size and tests

bin/inx-chronicle/src/stardust_inx/cone_stream.rs, src/db/collections/block.rs, src/db/collections/outputs/indexer/mod.rs, src/db/collections/outputs/mod.rs, tests/block.rs
=> fix(db)!: remove `output_id` and `block_id`

src/db/collections/milestone.rs
=> chore(db)!: combine milestone index and timestamp

bin/inx-chronicle/src/api/extractors.rs, bin/inx-chronicle/src/api/stardust/history/extractors.rs, bin/inx-chronicle/src/api/stardust/indexer/extractors.rs
=> feat(api): deny unknown query fields

bin/inx-chronicle/src/api/stardust/core/routes.rs, src/db/collections/mod.rs, src/db/collections/outputs/mod.rs
=> fix(api): re-enable utxo-changes route

.github/workflows/canary.yml, bin/inx-chronicle/src/launcher.rs
=> fix(ci): use `cargo-hack` in `canary` builds

.github/workflows/coverage.yml
=> fix(ci): install `protoc` in `coverage` workflow

src/bin/inx-chronicle/api/stardust/core/routes.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/collections/block.rs, src/db/collections/ledger_update.rs, src/db/collections/milestone.rs, src/db/collections/outputs/indexer/mod.rs, src/db/collections/outputs/mod.rs, src/db/collections/treasury.rs, src/db/mongodb.rs, src/types/ledger/block_metadata.rs, src/types/ledger/output_metadata.rs, tests/block.rs
=> feat(db)!: proper use of `_id` fields

src/db/collections/outputs/mod.rs
=> feat(db): use `db.run_command` for faster bulk updates

.github/workflows/test-iota-docs-build.yml, documentation/README.md, documentation/docusaurus.config.js, documentation/package.json, documentation/yarn.lock
Fixed and update everything including two broken links. I referenced the document on GitHub directly as you can't really reference a file outside of the docs folder (if you not import it)
=> Fix docs setup

src/bin/inx-chronicle/stardust_inx/error.rs, src/bin/inx-chronicle/stardust_inx/mod.rs
=> feat(inx): check for stale database before syncing

src/bin/inx-chronicle/api/stardust/analytics/responses.rs, src/bin/inx-chronicle/api/stardust/analytics/routes.rs
=> fix!(api): return Bech32s in `richest-addresses` endpoint

src/bin/inx-chronicle/api/stardust/explorer/routes.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/collections/ledger_update.rs, src/db/collections/outputs/indexer/mod.rs, src/db/collections/outputs/mod.rs, src/types/stardust/block/output/mod.rs, src/types/stardust/block/payload/transaction.rs, tests/outputs.rs
This reverts commit 493ab8e2caf06be95a8b51568ba1b7dd6a496827.
=> fix(db): revert 493ab8e due to regression

docker/assets/grafana/dashboards/chronicle_dashboard.json, docker/assets/prometheus/prometheus.yml, docker/docker-compose.nest.yml, docker/docker-compose.yml
=> feat(metrics): add MongoDB panel to Grafana

src/bin/inx-chronicle/api/stardust/core/routes.rs, src/bin/inx-chronicle/api/stardust/explorer/routes.rs, src/db/collections/ledger_update.rs, src/db/collections/milestone.rs, src/db/collections/outputs/indexer/mod.rs
This PR carries over the output id bug fix from https://github.com/iotaledger/inx-chronicle/commit/493ab8e2caf06be95a8b51568ba1b7dd6a496827.
=> fix(db): use `_id` instead of `metadata.output_id`

src/db/collections/outputs/indexer/mod.rs
=> fix(db): create indexes on `.milestone_index`

CHANGELOG.md, README.md, documentation/api/api-analytics.yml, documentation/api/api-explorer.yml, documentation/docs/changelog.md, documentation/docs/reference/api.md, documentation/docusaurus.config.js, documentation/sidebars.js
Fixed the core API links in the docs
=> doc(wiki): fix broken links

src/db/collections/outputs/mod.rs
=> fix(db): add index on `metadata.block_id`

.github/PULL_REQUEST_TEMPLATE/fast_track_pr.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Here is some (still very rough) initial proposal. Feel free to push changes anytime!
=> chore(gh): add pull request (reviewer) templates

src/db/collections/outputs/mod.rs
=> fix(api): deserialization error in `api/analytics/v2/ledger/storage-deposit`

.github/pull_request_template.md, config.template.toml, src/bin/inx-chronicle/api/config.rs, src/bin/inx-chronicle/config.rs, src/bin/inx-chronicle/metrics.rs, src/bin/inx-chronicle/stardust_inx/config.rs, src/db/mongodb/mod.rs
=> feat: improve MongoDb connection string handling

.github/pull_request_template.md, src/bin/inx-chronicle/config.rs
=> fix: revert `deny_unknown_fields` for top-level of config

config.template.toml, documentation/docs/reference/authentication.md, src/bin/inx-chronicle/api/config.rs
=> chore(docs): improve JWT docs and remove unnecessary config

.github/pull_request_template.md
And the nit-picking award goes to ....
=> chore(templates): change instruction

src/db/collections/milestone.rs
=> fix(db): fix unwind stage in receipt queries

src/bin/inx-chronicle/api/stardust/analytics/routes.rs, src/db/collections/mod.rs, src/db/collections/outputs/mod.rs, src/types/stardust/block/output/alias.rs, src/types/stardust/block/output/basic.rs, src/types/stardust/block/output/foundry.rs, src/types/stardust/block/output/mod.rs, src/types/stardust/block/output/nft.rs, src/types/stardust/block/output/treasury.rs, src/types/stardust/block/payload/milestone/mod.rs, src/types/stardust/block/payload/mod.rs, src/types/stardust/block/payload/tagged_data.rs, src/types/stardust/block/payload/transaction.rs, src/types/stardust/block/payload/treasury_transaction.rs
=> feat(types): improve and test encoding of `KIND`

src/bin/inx-chronicle/stardust_inx/mod.rs
=> fix(inx): fix missing milestone field

Cargo.lock, Cargo.toml
=> fix(security): disable `rustc-serialize` feature

docker/assets/grafana/dashboards/analytics_dashboard.json, docker/assets/grafana/datasources/influx_ds.yml
Please check if the dashboard works for you now.
=> feat(grafana): add InfluxDB data source

Cargo.lock, Cargo.toml, src/bin/inx-chronicle/process.rs
This PR just fixes building some feature variations that didn't pass `cargo check-all-features`.
=> fix(build): add missing feature dependencies

docker/assets/grafana/dashboards/analytics_dashboard.json, src/db/collections/analytics/influx.rs, src/db/collections/analytics/mod.rs, src/db/collections/outputs/mod.rs, tests/outputs_claiming.rs
=> fix(analytics): flip claimed to unclaimed analytics

Cargo.lock, src/bin/inx-chronicle/api/stardust/core/routes.rs, src/types/stardust/block/output/alias.rs, src/types/stardust/block/output/nft.rs
=> fix(deps)!: update `iota-types` to change packing order of `RentStructure`

Cargo.toml, config.template.toml, src/bin/inx-chronicle/cli.rs, src/bin/inx-chronicle/config.rs, src/bin/inx-chronicle/error.rs, src/bin/inx-chronicle/main.rs, src/bin/inx-chronicle/stardust_inx/error.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/collections/analytics/mod.rs, src/db/collections/metrics/mod.rs, src/db/influxdb/mod.rs, src/db/mod.rs, src/types/stardust/milestone.rs, src/types/tangle/milestone.rs
=> feat(cli): split `influxdb` feature properly

docker/assets/grafana/dashboards/chronicle_dashboard.json
=> feat(grafana): improve display of `sync_time`

config.template.toml, documentation/docs/reference/api.md
=> chore(cleanup): remove Analytics API remnants

docker/assets/grafana/dashboards/analytics_dashboard.json
=> fix(grafana): Further improves the performance of the analytics dashboard

documentation/api/api-explorer.yml
=> fix(docs): cleanup explorer docs

docker/assets/grafana/dashboards/analytics_dashboard.json, src/db/collections/analytics/influx.rs, src/db/collections/analytics/mod.rs, src/db/collections/block.rs, src/db/collections/outputs/mod.rs, tests/blocks.rs, tests/outputs.rs
=> feat(influxdb)!: consolidate queries

src/bin/inx-chronicle/main.rs
=> fix(logging): set up logging before subcommands are executed

src/bin/inx-chronicle/cli.rs
Since it's a potentially long-running command we probably want to be able to abort it.
=> feat(cli): allow cancellation of fill-analytics tool

config.template.toml, docker/assets/grafana/dashboards/analytics_dashboard.json, docker/assets/grafana/dashboards/chronicle_dashboard.json, docker/assets/grafana/datasources/influx_analytics_ds.yml, docker/assets/grafana/datasources/influx_metrics_ds.yml, docker/assets/influxdb/init.iql, docker/docker-compose.yml, src/bin/inx-chronicle/cli.rs, src/bin/inx-chronicle/main.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/collections/analytics/influx.rs, src/db/influxdb/mod.rs
=> feat(influxdb)!: divide analytics and metrics databases

Cargo.lock, Cargo.toml, src/bin/inx-chronicle/api/stardust/core/responses.rs, src/bin/inx-chronicle/api/stardust/core/routes.rs, src/types/ledger/output_metadata.rs, src/types/tangle/protocol.rs
Please make sure that the mapping of the key/data factors is correct. 🙏
=> chore(deps): bump dependencies

Cargo.lock, Cargo.toml, docker/docker-compose.yml, src/bin/inx-chronicle/main.rs
=> chore(refactor): remove `opentelemetry` feature

docker/assets/grafana/dashboards/analytics_dashboard.json
* Closes #952.
Unfortunately, it does not seem possible to add the units to the axis, which is why I added them to the panel title.
=> feat(grafana): add time interval to panel titles

Cargo.lock, Cargo.toml, src/bin/inx-chronicle/api/auth.rs, src/bin/inx-chronicle/api/extractors.rs, src/bin/inx-chronicle/api/mod.rs, src/bin/inx-chronicle/api/router.rs, src/bin/inx-chronicle/api/routes.rs, src/bin/inx-chronicle/api/stardust/core/routes.rs, src/bin/inx-chronicle/api/stardust/explorer/extractors.rs, src/bin/inx-chronicle/api/stardust/explorer/routes.rs, src/bin/inx-chronicle/api/stardust/indexer/extractors.rs, src/bin/inx-chronicle/api/stardust/indexer/routes.rs, src/bin/inx-chronicle/api/stardust/mod.rs, src/bin/inx-chronicle/api/stardust/poi/routes.rs
=> fix(api): revert axum upgrade

.cargo/config.toml, Cargo.toml, src/bin/inx-chronicle/api/error.rs, src/bin/inx-chronicle/api/extractors.rs, src/bin/inx-chronicle/api/mod.rs, src/bin/inx-chronicle/api/routes.rs, src/bin/inx-chronicle/cli.rs, src/bin/inx-chronicle/config.rs, src/bin/inx-chronicle/main.rs, src/db/mod.rs, src/types/ledger/inclusion_state.rs, src/types/mod.rs
=> chore(features): remove `stardust` feature

.github/workflows/_test_int.yml, docker/docker-compose.yml, src/bin/inx-chronicle/cli.rs, src/bin/inx-chronicle/config.rs, src/bin/inx-chronicle/stardust_inx/config.rs, src/bin/inx-chronicle/stardust_inx/error.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/influxdb/config.rs, src/db/mongodb/config.rs, src/db/mongodb/mod.rs, tests/common/mod.rs
=> feat(config)!: Remove ambiguity from CLI config

src/bin/inx-chronicle/api/stardust/core/routes.rs, src/db/collections/block.rs, tests/blocks.rs
=> feat(api): add block metadata route for included transactions

src/bin/inx-chronicle/cli.rs, src/bin/inx-chronicle/main.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/influxdb/config.rs, src/db/influxdb/mod.rs
=> feat(analytics): selective analytics for INX connections

.license_template
=> fix(ci): generalize license template regex

src/bin/inx-chronicle/cli.rs, src/bin/inx-chronicle/stardust_inx/error.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/db/collections/application_state.rs, src/db/collections/ledger_update.rs, src/db/collections/mod.rs, src/types/ledger/output_metadata.rs, src/types/tangle/milestone.rs
=> fix(analytics): only calculate analytics after chronicle is synced

src/db/collections/milestone.rs
=> fix(db): slow newest/oldest milestone query

src/db/collections/analytics/address_balance.rs, src/db/collections/analytics/base_token.rs, src/db/collections/analytics/block_activity.rs, src/db/collections/analytics/daily_active_addresses.rs, src/db/collections/analytics/output_activity.rs, src/db/collections/analytics/unclaimed_tokens.rs, src/db/collections/analytics/unlock_condition.rs, src/db/collections/block.rs, src/db/collections/milestone.rs, src/db/collections/outputs/indexer/mod.rs, src/db/collections/outputs/mod.rs
=> chore(db): remove unrequired allocations

.github/workflows/_features.yml, .github/workflows/canary.yml, .github/workflows/ci.yml
=> chore(ci): `check-all-features` on ready PRs

src/bin/inx-chronicle/stardust_inx/error.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/tangle/ledger_updates.rs, src/tangle/sources/inx.rs, src/tangle/sources/mongodb.rs
=> `Vec`-based `LedgerUpdateStore`

src/analytics/mod.rs, src/bin/inx-chronicle/stardust_inx/mod.rs, src/tangle/milestone_stream.rs, src/tangle/mod.rs, src/tangle/sources/mongodb.rs
=> Cache ledger updates

src/analytics/ledger/active_addresses.rs, src/analytics/ledger/address_balance.rs, src/analytics/ledger/base_token.rs, src/analytics/ledger/ledger_size.rs, src/analytics/ledger/mod.rs, src/analytics/ledger/output_activity.rs, src/analytics/mod.rs, src/db/collections/analytics/mod.rs, src/db/collections/analytics/output_activity.rs
=> implement foundry activity analytics and cleanup output activity impl

src/bin/inx-chronicle/stardust_inx/mod.rs
=> chore(db): remove temp migration code

.gitignore, documentation/docs/reference/authentication.md, documentation/docs/reference/environment.md
=> fix(docs): Remove `config.toml` remnants

src/bin/inx-chronicle/api/stardust/poi/routes.rs, src/db/collections/block.rs, tests/blocks.rs, tests/data/blocks_ms_2418187.json, tests/data/blocks_ms_2418807.json
=> fix(api): refactor block queries to avoid lookups

docker/assets/grafana/dashboards/analytics_dashboard.json, src/analytics/influx.rs, src/analytics/ledger/ledger_size.rs, src/analytics/ledger/mod.rs, src/analytics/ledger/unclaimed_tokens.rs, src/analytics/ledger/unlock_conditions.rs
=> feat(analytics): rename value fields to amount

src/bin/inx-chronicle/cli/analytics.rs
=> fix(metrics): Start measurement before fetching milestone

src/bin/inx-chronicle/api/stardust/explorer/routes.rs, src/db/collections/block.rs, tests/blocks.rs
=> fix(db): fix slow get block children query

src/bin/inx-chronicle/cli/mod.rs
=> fix(cli): fix regression at startup

CHANGELOG.md, Cargo.lock, Cargo.toml
=> chore: release `v1.0.0-beta.35`

src/db/mongodb/collections/block.rs, src/db/mongodb/collections/milestone.rs, src/db/mongodb/collections/outputs/mod.rs
Clean up a few leftover instances of Vec allocations in aggregate calls.
=> chore(db): clean up aggregate calls

src/bin/inx-chronicle/migrations/migrate_1.rs, src/db/mongodb/collections/block.rs
=> fix(db): remove parents index and fix the query

src/bin/inx-chronicle/migrations/mod.rs
=> fix(logging): cannot migrate error message

docker/docker-compose.yml
Docker image `grafana` changed to `grafana-oss`.
=> chore(docker): update grafana image to oss

Cargo.lock, src/analytics/ledger/active_addresses.rs, src/analytics/ledger/address_balance.rs, src/analytics/ledger/ledger_size.rs, src/analytics/mod.rs, src/bin/inx-chronicle/api/error.rs, src/bin/inx-chronicle/cli/analytics.rs, src/bin/inx-chronicle/inx/influx/analytics.rs
=> fix(analytics): account for outputs with amount less than min deposit
